########################################################################
# Comparison tests
# For DDL/DML workflow can only be single-threaded.
# For read-only workflow RQG_THREADS can be re-defined
########################################################################

trigger: none

jobs:

#########
# Download or build baseline server
- template: jobs/prepare-server.yml
  parameters:
    name: 'Download_or_Build_Baseline'
    SERVER_BRANCH: $(BASELINE_BRANCH)
    SERVER_REVNO: $(BASELINE_REVISION)
    BASEDIR: $(HOME)/baseline
    BUILD_ARTIFACT_NAME: 'baseline'

#########
# Upload to FTP
- template: jobs/upload-to-ftp.yml
  parameters:
    name: 'Upload_baseline_to_FTP'
    artifactName: 'baseline'
    dependencies:
    - 'Download_or_Build_Baseline'
    condition: and(succeeded(), ne(dependencies.Download_or_Build_Server.outputs['ftp_download.BINARIES_FROM_FTP'], 'true'))

#########
# Download or build server under test
- template: jobs/prepare-server.yml
  parameters:
    name: 'Download_or_Build_Server'
    SERVER_BRANCH: $(SERVER_BRANCH)
    SERVER_REVNO: $(SERVER_REVNO)
    BASEDIR: $(HOME)/server

#########
# Upload to FTP
- template: jobs/upload-to-ftp.yml
  parameters:
    name: 'Upload_build_to_FTP'
    artifactName: 'build'
    dependencies:
    - 'Download_or_Build_Server'
    condition: and(succeeded(), ne(dependencies.Download_or_Build_Server.outputs['ftp_download.BINARIES_FROM_FTP'], 'true'))

#########
- job: Test
  timeoutInMinutes: 0
  dependsOn: Download_or_Build_Server
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:

      '001':
        RQG_GRAMMAR: 'conf/runtime/metadata_stability.yy'
        RQG_GENDATA: 'conf/runtime/metadata_stability.zz'
        RQG_THREADS: 1

      '002':
        RQG_GRAMMAR: 'conf/runtime/performance_schema.yy'
        MYSQLD_JOB_OPTIONS: '--mysqld=--performance-schema'
        RQG_THREADS: 1

      '003':
        RQG_GRAMMAR: 'conf/runtime/information_schema.yy'
        RQG_THREADS: 1

      '004':
        RQG_GRAMMAR: 'conf/engines/many_indexes.yy'
        RQG_GENDATA: 'conf/engines/many_indexes.zz'
        RQG_ENGINE: InnoDB,Aria
        RQG_THREADS: 1

      '005':
        RQG_GRAMMAR: 'conf/engines/engine_stress.yy'
        RQG_GENDATA: 'conf/engines/engine_stress.zz'
        RQG_ENGINE: InnoDB,Aria,MyISAM
        RQG_THREADS: 1

      '006':
        RQG_GRAMMAR: 'conf/partitioning/partitions.yy'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '007':
        RQG_GRAMMAR: 'conf/partitioning/partition_pruning.yy'
        RQG_GENDATA: 'conf/partitioning/partition_pruning.zz'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '008':
        RQG_GRAMMAR: 'conf/replication/replication.yy'
        RQG_GENDATA: 'conf/replication/replication-5.1.zz'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '009':
        RQG_GRAMMAR: 'conf/replication/replication-ddl_sql.yy'
        RQG_GENDATA: 'conf/replication/replication-ddl_data.zz'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '010':
        RQG_GRAMMAR: 'conf/replication/replication-dml_sql.yy'
        RQG_GENDATA: 'conf/replication/replication-dml_data.zz'
        RQG_THREADS: 1
        RQG_ENGINE: InnoDB

      '011':
        RQG_GRAMMAR: 'conf/runtime/connect_kill_sql.yy'
        RQG_GENDATA: 'conf/runtime/connect_kill_data.zz'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '012':
        RQG_GRAMMAR: 'conf/runtime/WL5004_sql.yy'
        RQG_GENDATA: 'conf/runtime/WL5004_data.zz'
        RQG_ENGINE: InnoDB
        RQG_THREADS: 1

      '013':
        RQG_GRAMMAR: 'conf/mariadb/optimizer.yy'
        RQG_ENGINE: InnoDB,Aria,MyISAM

      '014':
        RQG_GRAMMAR: 'conf/optimizer/updateable_views.yy'
        RQG_JOB_OPTIONS: '--skip-gendata'
        MYSQLD_JOB_OPTIONS: "--mysqld=--init-file=$ENV_RQG_HOME/conf/optimizer/updateable_views.init --mysqld=--default-storage-engine=MyISAM"
        RQG_ENGINE: MyISAM
        RQG_THREADS: 1

      '015':
        RQG_GRAMMAR: 'conf/mariadb/oltp-transactional.yy'
        RQG_GENDATA: 'conf/mariadb/oltp.zz'
        RQG_ENGINE: InnoDB,Aria
        RQG_THREADS: 1

      '016':
        RQG_GRAMMAR: 'conf/mariadb/oltp.yy'
        RQG_GENDATA: 'conf/mariadb/oltp.zz'
        RQG_ENGINE: MyISAM
        RQG_THREADS: 1

      '017':
        RQG_GRAMMAR: 'conf/mariadb/functions.yy'

      '018':
        RQG_GRAMMAR: 'conf/runtime/alter_online.yy'
        RQG_GENDATA: 'conf/runtime/alter_online.zz'
        RQG_THREADS: 1

      '019':
        RQG_GRAMMAR: 'conf/engines/innodb/full_text_search.yy'
        RQG_GENDATA: 'conf/engines/innodb/full_text_search.zz'
        RQG_ENGINE: InnoDB,Aria,MyISAM
        RQG_THREADS: 1

      '020':
        RQG_GRAMMAR: 'conf/engines/heap/heap_dml_single.yy'
        RQG_JOB_OPTIONS: '--skip-gendata'
        MYSQLD_JOB_OPTIONS: "--mysqld=--init-file=$ENV_RQG_HOME/conf/engines/heap/heap_dml_single.init"
        RQG_THREADS: 1

      '021':
        RQG_GRAMMAR: 'conf/engines/heap/heap_ddl_multi.yy'
        RQG_JOB_OPTIONS: '--skip-gendata'
        RQG_THREADS: 1

#      '022':
#        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
#        RQG_GENDATA: 'conf/temporal/temporal_functions.zz'
#        RQG_ENGINE: InnoDB,MyISAM
#        RQG_THREADS: 1

#      '023':
#        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
#        RQG_GENDATA: 'conf/temporal/temporal_functions.zz'
#        RQG_ENGINE: MyISAM
#        RQG_THREADS: 1

#      '032':
#        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
#        RQG_GENDATA: 'conf/temporal/temporal_functions-wl946.zz'
#        RQG_DURATION: 1200

#      '024':
#        RQG_GRAMMAR: 'conf/mariadb/generic-dml.yy'
#        RQG_GENDATA: '--gendata-advanced'
#        RQG_JOB_OPTIONS: '--skip-gendata'
#        RQG_ENGINE: InnoDB,MyISAM,Aria,HEAP
#        RQG_THREADS: 1

  steps:

  - template: steps/env.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'build'
      downloadPath: $(Build.ArtifactStagingDirectory)
    displayName: 'Download build from artifacts'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/build/build-*.tar.gz'
      destinationFolder: $(env.BASEDIR)
    displayName: 'Extract build'

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'baseline'
      downloadPath: $(Build.ArtifactStagingDirectory)
    displayName: 'Download baseline from artifacts'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/baseline/build-*.tar.gz'
      destinationFolder: $(HOME)/baseline
    displayName: 'Extract baseline'

  - template: steps/install-deb-packages.yml
    parameters:
      INSTALLATION_SET: 'runtime'

  - template: steps/clone-test-tools.yml

  - template: steps/run-rqg-test.yml
    parameters:
      TRIAL_OPTIONS: "--basedir1=$(env.BASEDIR) --basedir2=$(HOME)/baseline --vardir1=$(env.LOGDIR)/vardir1 --vardir2=$(env.LOGDIR)/vardir2"

#########
# Print summary
- template: jobs/test-report.yml
  parameters:
    dependencies:
    - Test
