########################################################################
# Job to download MariaDB server binaries from FTP or build from sources
########################################################################

parameters:
  vmImage: 'Ubuntu 20.04'
  name: 'Download_or_Build_Server'
  condition: succeeded()
  dependencies: []

  FTP_DOWNLOAD: 'ftp://hasky.askmonty.org/public/azure'
  BUILD_ARTIFACT_NAME: 'build'

jobs:

#-----------------------------------------------------------------------
# Try to download the server from FTP;
# if not found, then clone and build

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: ${{ parameters.condition }}
  dependsOn: ${{ parameters.dependencies }}

  steps:

  - template: ../steps/env.yml
    parameters:
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'dependencies','name','condition') }}:
          ${{ pair.key }}: ${{ pair.value }}

  # Make sure that required parameters are defined
  - bash: |
      if [ -z "$ENV_SERVER_REPO" ]; then
        echo "##vso[task.complete result=Failed]Missing value of \"SERVER_REPO\""
      fi
      if [ -z "$ENV_SERVER_BRANCH" ]; then
        echo "##vso[task.complete result=Failed]Missing value of \"SERVER_BRANCH\""
      fi
      if [ -z "$ENV_SERVER_REVNO" ]; then
        echo "##vso[task.complete result=Failed]Missing value of \"SERVER_REVNO\""
      fi
    displayName: Check for required parameters

  # Install libraries, clone and build server

  - template: ../steps/install-deb-packages.yml
    parameters:
      INSTALLATION_SET: 'build'
      condition: succeeded()

  - bash: |
      set -x
      srcdir=$HOME/src
      builddir=$HOME/out-of-source
      rm -rf $srcdir
      git init $srcdir
      cd $srcdir
      git fetch $ENV_SERVER_REPO $ENV_SERVER_REVNO_FULL
      git checkout FETCH_HEAD
      sed -i -e 's/define DEFAULT_MAX_CONN        64/define DEFAULT_MAX_CONN        256/' client/mysqltest.cc
      grep DEFAULT_MAX_CONN client/mysqltest.cc
      mkdir $builddir
      cd $builddir
      cmake $srcdir $ENV_CMAKE_OPTIONS -DCMAKE_INSTALL_PREFIX=$ENV_BASEDIR
      make -j5
      make install
      rm -rf $ENV_BASEDIR/mysql-test $ENV_BASEDIR/mariadb-test
      cd $srcdir
      echo $ENV_SERVER_BRANCH `git log -1 --abbrev=8 --pretty="%h"` > $ENV_BASEDIR/server.info
      echo $ENV_CMAKE_OPTIONS >> $ENV_BASEDIR/server.info
      filename=build-$ENV_SERVER_BRANCH-$ENV_SERVER_REVNO
      echo "Bintar filename to search for: $filename"
      echo "##vso[task.setvariable variable=BINTAR_NAME;isOutput=true]$filename"
    condition: succeeded()
    displayName: 'Clone and build server'
    name: build_server

  # Archive newly built binaries
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(env.BASEDIR)
      includeRootFolder: false
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile:  $(Build.ArtifactStagingDirectory)/$(build_server.BINTAR_NAME).tar.gz
    displayName: 'Create bintar'
    name: create_bintar
    condition: succeeded()

  # Store bintar as a build artifact
  # (in any case, be it downloaded or freshly built)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: ${{ parameters.BUILD_ARTIFACT_NAME }}
    displayName: 'Store build artifact'
    condition: succeeded()
