########################################################################
# Job to upload a build artifact to FTP
########################################################################

parameters:
  vmImage: 'Ubuntu 20.04'
  name: 'Upload_to_FTP'
  condition: succeeded()
  artifactName: 'build'
  FTP_URL: 'ftp://hasky.askmonty.org'
  FTP_UPLOAD_DIRECTORY: '/private/azure'
  FTP_USER: 'anonymous'
  FTP_PASSWORD: 'foo'
  dependencies: []

jobs:

#-----------------------------------------------------------------------
# Publish a build artifact to FTP

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: ${{ parameters.dependencies }}
  condition: ${{ parameters.condition }}
  # Storing to FTP is "best effort", it shouldn't affect tests
  continueOnError: true

  steps:
  # Get the artifact from build artifacts
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: ${{ parameters.artifactName }}
      downloadPath: $(Build.ArtifactStagingDirectory)

  # Upload to FTP
  - task: FtpUpload@1
    inputs:
      credentialsOption: 'inputs'
      serverUrl: '${{ parameters.FTP_URL }}'
      username: '${{ parameters.FTP_USER }}'
      password: '${{ parameters.FTP_PASSWORD }}'
      rootDirectory: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}'
      remoteDirectory: '${{ parameters.FTP_UPLOAD_DIRECTORY }}'
    displayName: 'Upload ${{ parameters.artifactName }} to FTP'
